In [ ]:
import numpy as np
import pandas as pd

# Banking Assigment with numpy

In [ ]:

bank_data = np.array([
    [2001,  5230.75, 720, 15,  5],
    [2002, 15890.50, 680, 22,  8],
    [2003,  2500.10, 650,  8,  2],
    [2004, 30250.00, 790, 30, 12],
    [2005,  8750.60, 710, 12,  4],
    [2006, 45000.90, 840, 40, 15],
    [2007, 11000.25, 695, 18,  6],
    [2008,  6700.00, 730, 10,  3],
    [2009, 22000.80, 765, 25, 10],
    [2010, 14500.40, 785, 28,  9]
])

In [ ]:
Customer_id=bank_data[:,0]
print(Customer_id)

Account_balance=bank_data[:,1]
print(Account_balance)

creadit_score=bank_data[:,2]
print(creadit_score)

Transaction_count=bank_data[:,3]
print(Transaction_count)

Years_Active=bank_data[:,4]
print(Years_Active)

[2001. 2002. 2003. 2004. 2005. 2006. 2007. 2008. 2009. 2010.]
[ 5230.75 15890.5   2500.1  30250.    8750.6  45000.9  11000.25  6700.
 22000.8  14500.4 ]
[720. 680. 650. 790. 710. 840. 695. 730. 765. 785.]
[15. 22.  8. 30. 12. 40. 18. 10. 25. 28.]
[ 5.  8.  2. 12.  4. 15.  6.  3. 10.  9.]


In [ ]:
first_row=bank_data[0]
print(first_row)

second_row=bank_data[1]
print(second_row)

third_row=bank_data[2]
print(third_row)

fourth_row=bank_data[3]
print(fourth_row)

fifth_row=bank_data[4]
print(fifth_row)

sixth_row=bank_data[5]
print(sixth_row)

seventh_row=bank_data[6]
print(seventh_row)

eighth_row=bank_data[7]
print(eighth_row)

ninth_row=bank_data[8]
print(ninth_row)

tenth_row=bank_data[9]
print(tenth_row)

[2.00100e+03 5.23075e+03 7.20000e+02 1.50000e+01 5.00000e+00]
[2.00200e+03 1.58905e+04 6.80000e+02 2.20000e+01 8.00000e+00]
[2.0030e+03 2.5001e+03 6.5000e+02 8.0000e+00 2.0000e+00]
[2.004e+03 3.025e+04 7.900e+02 3.000e+01 1.200e+01]
[2.0050e+03 8.7506e+03 7.1000e+02 1.2000e+01 4.0000e+00]
[2.00600e+03 4.50009e+04 8.40000e+02 4.00000e+01 1.50000e+01]
[2.007000e+03 1.100025e+04 6.950000e+02 1.800000e+01 6.000000e+00]
[2.008e+03 6.700e+03 7.300e+02 1.000e+01 3.000e+00]
[2.00900e+03 2.20008e+04 7.65000e+02 2.50000e+01 1.00000e+01]
[2.01000e+03 1.45004e+04 7.85000e+02 2.80000e+01 9.00000e+00]


####Question 1: Array Creation and Manipulation

In [ ]:
print(np.eye(4,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(np.zeros(8))

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print(np.ones(6))

[1. 1. 1. 1. 1. 1.]


In [ ]:
print(np.arange(0,15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
print(np.linspace(0,100,8))

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


####Question 2: Array Attributes and Information

In [ ]:
print(bank_data.shape)

(10, 5)


In [ ]:
print(bank_data.dtype)

float64


In [ ]:
print(bank_data.size)

50


In [ ]:
print(bank_data.ndim)

2


In [ ]:
print(bank_data.nbytes)

400


####Question 3: Indexing and Slicing

In [ ]:
print(bank_data[0].astype(int))

[2001 5230  720   15    5]


In [ ]:
print(bank_data[-1].astype(int))

[ 2010 14500   785    28     9]


In [ ]:
print(bank_data[:,1].astype(int))

[ 5230 15890  2500 30250  8750 45000 11000  6700 22000 14500]


In [ ]:
print(bank_data[:4,:3].astype(int))

[[ 2001  5230   720]
 [ 2002 15890   680]
 [ 2003  2500   650]
 [ 2004 30250   790]]


In [ ]:
print(bank_data[2:7].astype(int))

[[ 2003  2500   650     8     2]
 [ 2004 30250   790    30    12]
 [ 2005  8750   710    12     4]
 [ 2006 45000   840    40    15]
 [ 2007 11000   695    18     6]]


####Question 4: Mathematical Operations

In [ ]:
Sum_of_Account_balance=np.sum(bank_data[:,1])
print(Sum_of_Account_balance)

161824.3


In [ ]:
mean_of_Account_balance=np.mean(bank_data[:,1])
print(mean_of_Account_balance)

16182.429999999998


In [ ]:
STD_of_Account_balance=np.std(bank_data[:,1])
print(STD_of_Account_balance)

12427.057700059173


In [ ]:
var_of_Account_balance=np.var(bank_data[:,1])
print(var_of_Account_balance)

154431763.0806


In [ ]:
median_of_Account_balance=np.median(bank_data[:,1])
print(median_of_Account_balance)

12750.325


####Question 5: Statistical Functions

In [ ]:
min_max_of_Account_balance=np.min(bank_data[:,1]),np.max(bank_data[:,1])
print(min_max_of_Account_balance)

(np.float64(2500.1), np.float64(45000.9))


In [ ]:
min_max_of_credit_score=np.min(bank_data[:,2]),np.max(bank_data[:,2])
print(min_max_of_Account_balance)

(np.float64(2500.1), np.float64(45000.9))


In [ ]:
percentiles = np.percentile(bank_data[:, 1], [25, 50, 75])
print("25th percentile:", percentiles[0])
print("50th percentile (median):", percentiles[1])
print("75th percentile:", percentiles[2])

25th percentile: 7212.65
50th percentile (median): 12750.325
75th percentile: 20473.225


In [ ]:
cor_AB_CS=np.correlate(bank_data[:,1],bank_data[:,2])
print(cor_AB_CS)

[1.24857527e+08]


In [ ]:
cov_AB_CS=np.cov(bank_data[:,1],bank_data[:,2])
print(cov_AB_CS)

[[1.71590848e+08 6.30436644e+05]
 [6.30436644e+05 3.35027778e+03]]


####Question 6: Array Reshaping and Manipulation

In [ ]:
print(bank_data.reshape(5,10).astype(int))

[[ 2001  5230   720    15     5  2002 15890   680    22     8]
 [ 2003  2500   650     8     2  2004 30250   790    30    12]
 [ 2005  8750   710    12     4  2006 45000   840    40    15]
 [ 2007 11000   695    18     6  2008  6700   730    10     3]
 [ 2009 22000   765    25    10  2010 14500   785    28     9]]


In [ ]:
print(bank_data.flatten().astype(int))

[ 2001  5230   720    15     5  2002 15890   680    22     8  2003  2500
   650     8     2  2004 30250   790    30    12  2005  8750   710    12
     4  2006 45000   840    40    15  2007 11000   695    18     6  2008
  6700   730    10     3  2009 22000   765    25    10  2010 14500   785
    28     9]


In [ ]:
print(bank_data.T.astype(int))

[[ 2001  2002  2003  2004  2005  2006  2007  2008  2009  2010]
 [ 5230 15890  2500 30250  8750 45000 11000  6700 22000 14500]
 [  720   680   650   790   710   840   695   730   765   785]
 [   15    22     8    30    12    40    18    10    25    28]
 [    5     8     2    12     4    15     6     3    10     9]]


In [ ]:
split_arrays = np.vsplit(bank_data, 2)
for arr in split_arrays:
    print(arr.astype(int))

[[ 2001  5230   720    15     5]
 [ 2002 15890   680    22     8]
 [ 2003  2500   650     8     2]
 [ 2004 30250   790    30    12]
 [ 2005  8750   710    12     4]]
[[ 2006 45000   840    40    15]
 [ 2007 11000   695    18     6]
 [ 2008  6700   730    10     3]
 [ 2009 22000   765    25    10]
 [ 2010 14500   785    28     9]]


In [ ]:
h_split_arrays = np.hsplit(bank_data, 2)
for arr in h_split_arrays:
    print(arr.astype(int))

ValueError: array split does not result in an equal division

####Question 7: Logical Operations and Filtering

In [ ]:
Ab_greater_10000=bank_data[bank_data[:,1]>10000]
print(Ab_greater_10000.astype(int))

[[ 2002 15890   680    22     8]
 [ 2004 30250   790    30    12]
 [ 2006 45000   840    40    15]
 [ 2007 11000   695    18     6]
 [ 2009 22000   765    25    10]
 [ 2010 14500   785    28     9]]


In [ ]:
CS_greater_800=bank_data[bank_data[:,2]>800]
print(CS_greater_800.astype(int))

[[ 2006 45000   840    40    15]]


In [ ]:
TCG50_CSL750=bank_data[(bank_data[:,3]>50)&(bank_data[:,2]<750)]
print(TCG50_CSL750.astype(int))

[]


In [ ]:
customers_AB_G10L_L10K = bank_data[(bank_data[:, 1] >= 10000) & (bank_data[:, 1] <= 100000)]
num_customers = customers_AB_G10L_L10K.shape[0]
print(num_customers)

6


In [ ]:
customers_high_credit_score = np.max(bank_data[:,2])
print(customers_high_credit_score)
index_C_HCS = np.where(bank_data[:, 2] == customers_high_credit_score)
print(index_C_HCS)

840.0
(array([5]),)


####Question 8: Sorting and Searching

In [ ]:
sorted_bank_data = bank_data[bank_data[:, 1].argsort()]
print(sorted_bank_data.astype(int))

[[ 2003  2500   650     8     2]
 [ 2001  5230   720    15     5]
 [ 2008  6700   730    10     3]
 [ 2005  8750   710    12     4]
 [ 2007 11000   695    18     6]
 [ 2010 14500   785    28     9]
 [ 2002 15890   680    22     8]
 [ 2009 22000   765    25    10]
 [ 2004 30250   790    30    12]
 [ 2006 45000   840    40    15]]


In [ ]:
sorted_bank_data2 = bank_data[bank_data[:, 1].argsort()[::-1]]
print(sorted_bank_data2.astype(int))

[[ 2006 45000   840    40    15]
 [ 2004 30250   790    30    12]
 [ 2009 22000   765    25    10]
 [ 2002 15890   680    22     8]
 [ 2010 14500   785    28     9]
 [ 2007 11000   695    18     6]
 [ 2005  8750   710    12     4]
 [ 2008  6700   730    10     3]
 [ 2001  5230   720    15     5]
 [ 2003  2500   650     8     2]]


In [ ]:
sorted_indices = np.argsort(bank_data[:, 4])
print(sorted_indices)
sorted_by_years_active = bank_data[sorted_indices]
print(sorted_by_years_active.astype(int))

[2 7 4 0 6 1 9 8 3 5]
[[ 2003  2500   650     8     2]
 [ 2008  6700   730    10     3]
 [ 2005  8750   710    12     4]
 [ 2001  5230   720    15     5]
 [ 2007 11000   695    18     6]
 [ 2002 15890   680    22     8]
 [ 2010 14500   785    28     9]
 [ 2009 22000   765    25    10]
 [ 2004 30250   790    30    12]
 [ 2006 45000   840    40    15]]


In [ ]:
sorted_by_balance = bank_data[bank_data[:, 1].argsort()[::-1]]
second_highest_balance_customer = sorted_by_balance[1]
print(second_highest_balance_customer.astype(int))

[ 2004 30250   790    30    12]


In [ ]:
Low_Transaction_count=np.min(bank_data[:,3])
print(Low_Transaction_count)
index_Low_Transaction_count=np.where(bank_data[:,3]==Low_Transaction_count)
print(index_Low_Transaction_count)

8.0
(array([2]),)


####Question 9: Mathematical Functions

In [ ]:
Absolute_of_BD=np.absolute(bank_data)
print(Absolute_of_BD.astype(int))

[[ 2001  5230   720    15     5]
 [ 2002 15890   680    22     8]
 [ 2003  2500   650     8     2]
 [ 2004 30250   790    30    12]
 [ 2005  8750   710    12     4]
 [ 2006 45000   840    40    15]
 [ 2007 11000   695    18     6]
 [ 2008  6700   730    10     3]
 [ 2009 22000   765    25    10]
 [ 2010 14500   785    28     9]]


In [ ]:
Sqrt_of_Bd=np.sqrt(bank_data[:,1])
print(Sqrt_of_Bd.astype(int))

[ 72 126  50 173  93 212 104  81 148 120]


In [ ]:
square_of_credit_scores = np.square(bank_data[:, 2])
print(square_of_credit_scores.astype(int))

[518400 462400 422500 624100 504100 705600 483025 532900 585225 616225]


In [ ]:
TC_exp_of_all=np.exp(bank_data[:,3])
print(TC_exp_of_all.astype(int))

[           3269017         3584912846               2980
     10686474581524             162754 235385266837020000
           65659969              22026        72004899337
      1446257064291]


In [ ]:
log_of_account_balances = np.log(bank_data[:, 1])
print(log_of_account_balances)

[ 8.56230995  9.67347673  7.82408601 10.31725146  9.07687755 10.71443777
  9.30567328  8.80986281  9.9988341   9.58193151]


####Question 10: Advanced Operations

In [ ]:
CumulativeSum_AB=np.cumsum(bank_data[:,1])
print(CumulativeSum_AB.astype(int))

[  5230  21121  23621  53871  62621 107622 118623 125323 147323 161824]


In [ ]:
Cumulativeproduct_AB=np.cumprod(bank_data[:,3])
print(Cumulativeproduct_AB.astype(int))

[           15           330          2640         79200        950400
      38016000     684288000    6842880000  171072000000 4790016000000]


In [ ]:
diff_Consection_AB=np.diff(bank_data[:,1])
print(diff_Consection_AB.astype(int))

[ 10659 -13390  27749 -21499  36250 -34000  -4300  15300  -7500]


In [ ]:
Gradient_Ab=np.gradient(bank_data[:,1])
print(Gradient_Ab.astype(int))

[ 10659  -1365   7179   3125   7375   1124 -19150   5500   3900  -7500]


In [ ]:
Histogram_AB=np.histogram(bank_data[:,1],bins=5)
print(Histogram_AB)

(array([5, 2, 1, 1, 1]), array([ 2500.1 , 11000.26, 19500.42, 28000.58, 36500.74, 45000.9 ]))


####Question 11: Random Numbers and Simulation

In [ ]:
Gen_six_integer=np.random.randint(1,100,6)
print(Gen_six_integer)

[99 67 42 43 47  4]


In [ ]:
Gen_six_floatr=np.random.rand(6)
print(Gen_six_floatr)

[0.42738847 0.27593488 0.120439   0.77944958 0.78031598 0.61412214]


In [ ]:
random_normal = np.random.normal(loc=700, scale=100, size=6)
print(random_normal)

[589.56707162 645.68349555 652.20659262 731.11915204 649.52875223
 721.07645825]


In [ ]:
np.random.shuffle(bank_data)
print(bank_data.astype(int))

[[ 2007 11000   695    18     6]
 [ 2010 14500   785    28     9]
 [ 2003  2500   650     8     2]
 [ 2004 30250   790    30    12]
 [ 2009 22000   765    25    10]
 [ 2005  8750   710    12     4]
 [ 2001  5230   720    15     5]
 [ 2006 45000   840    40    15]
 [ 2002 15890   680    22     8]
 [ 2008  6700   730    10     3]]


In [ ]:
np.random.seed(123)
random_numbers = np.random.randint(4)
print(random_numbers)

2


####Question 12: Linear Algebra Operations

In [ ]:
Dot_Product_AB_CS=np.dot(Account_balance,creadit_score)
print(Dot_Product_AB_CS)

124857526.75


In [ ]:
Cross_product_2Rows=np.cross(fifth_row,second_row)
print(Cross_product_2Rows)

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [ ]:
Norm_AB=np.linalg.norm(Account_balance)
print(Norm_AB)

64521.53158330171


In [ ]:
Matrix_3X3=np.array([[1,2,3],
 [4,5,6],
  [7,8,9]])
print(Matrix_3X3)
Matrix_3X3_determinant=np.linalg.det(Matrix_3X3)
print(Matrix_3X3_determinant)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


In [ ]:
# Create another invertible 3x3 matrix (a different example)
invertible_matrix_2 = np.array([[3, 1, 4],
                                [1, 5, 9],
                                [2, 6, 5]])

print("Created a different invertible 3x3 matrix:")
print(invertible_matrix_2)

# Calculate the inverse of this matrix
inverse_of_matrix_2 = np.linalg.inv(invertible_matrix_2)

print("\nInverse of the second matrix:")
print(inverse_of_matrix_2.astype(int))

Created a different invertible 3x3 matrix:
[[3 1 4]
 [1 5 9]
 [2 6 5]]

Inverse of the second matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


####Question 13: String Operations

In [ ]:
Customer_id_String=Customer_id.astype(str)
print(Customer_id_String)

['2007.0' '2010.0' '2003.0' '2004.0' '2009.0' '2005.0' '2001.0' '2006.0'
 '2002.0' '2008.0']


In [ ]:
Customer_id_Contain=Customer_id==100
print(Customer_id_Contain)

[False False False False False False False False False False]


In [ ]:
customer_id_uppercase = np.char.upper(Customer_id_String)
print(customer_id_uppercase)

['2007.0' '2010.0' '2003.0' '2004.0' '2009.0' '2005.0' '2001.0' '2006.0'
 '2002.0' '2008.0']


In [ ]:
Len_of_customer_id=np.char.str_len(Customer_id_String)
print(Len_of_customer_id)

[6 6 6 6 6 6 6 6 6 6]


In [ ]:
customer_id_replaced = np.char.replace(Customer_id_String, '5', 'CUST')
#customer_id_replaced = np.char.replace(customer_id_replaced, '10', 'CUST')
print(customer_id_replaced)

['2007.0' '2010.0' '2003.0' '2004.0' '2009.0' '200CUST.0' '2001.0'
 '2006.0' '2002.0' '2008.0']


####Question 14: Date and Time Operations

In [ ]:
years_active_months = Years_Active * 12
print(years_active_months.astype(int))

[ 72 108  24 144 120  48  60 180  96  36]


In [ ]:
Avg_years_active=np.mean(Years_Active)
print(Avg_years_active)

7.4


In [ ]:
Customer_Active_5Y=bank_data[Years_Active>5]
print(Customer_Active_5Y.astype(int))

[[ 2007 11000   695    18     6]
 [ 2010 14500   785    28     9]
 [ 2004 30250   790    30    12]
 [ 2009 22000   765    25    10]
 [ 2006 45000   840    40    15]
 [ 2002 15890   680    22     8]]


In [ ]:
Total_time_customer=np.sum(Years_Active)
print(Total_time_customer)

74.0


In [ ]:
Sortest_Customer_active=np.min(Years_Active)
print(Sortest_Customer_active)
Sortest_Customer_active_index=bank_data[Years_Active==Sortest_Customer_active]
print(Sortest_Customer_active_index.astype(int))

2.0
[[2003 2500  650    8    2]]


####Question 15: Advanced Array Operations

In [ ]:
interest = Account_balance * 0.05
print(interest.astype(int))
new_account_balances = Account_balance + interest
print(new_account_balances.astype(int))

[ 550  725  125 1512 1100  437  261 2250  794  335]
[11550 15225  2625 31762 23100  9188  5492 47250 16685  7035]


In [ ]:
low_of_AB=np.percentile(Account_balance,25)
print(low_of_AB)

high_of_AB=np.percentile(Account_balance,75)
print(high_of_AB)
balance_categories_AB = np.where(Account_balance < low_of_AB, 'Low Balance',
                              np.where(Account_balance < high_of_AB, 'Medium Balance', 'High Balance'))
print(balance_categories_AB)

7212.65
20473.225
['Medium Balance' 'Medium Balance' 'Low Balance' 'High Balance'
 'High Balance' 'Medium Balance' 'Low Balance' 'High Balance'
 'Medium Balance' 'Low Balance']


In [ ]:
low_of_CS=np.percentile(creadit_score,25)
print(low_of_CS)

high_of_CS=np.percentile(creadit_score,75)
print(high_of_CS)

conditions=[
    (creadit_score<low_of_CS),
    (creadit_score>=low_of_CS)&(creadit_score<high_of_CS),
    (creadit_score>=high_of_CS)
]

categories=['Low Credit Score','Medium Credit Score','High Credit Score']

credit_score_categories=np.select(conditions,categories,default='Unknown')
print(credit_score_categories)

698.75
780.0
['Low Credit Score' 'High Credit Score' 'Low Credit Score'
 'High Credit Score' 'Medium Credit Score' 'Medium Credit Score'
 'Medium Credit Score' 'High Credit Score' 'Low Credit Score'
 'Medium Credit Score']


In [ ]:
low_of_AB=np.percentile(Account_balance,25)
print(low_of_AB)

high_of_Ab=np.percentile(Account_balance,75)
print(high_of_AB)

conditions=[
    (Account_balance<low_of_AB),
    (Account_balance>=low_of_AB)&(Account_balance<high_of_AB),
    (Account_balance>=high_of_AB)
]
# def calculate_low_interest(x):
#   return x * 0.03

# def calculate_medium_interest(x):
#   return x * 0.05

# def calculate_high_interest(x):
#   return x * 0.07
# functions=[
#     calculate_low_interest,
#     calculate_medium_interest,
#     calculate_high_interest
# ]

functions=[
    lambda x: x * 0.03,
    lambda x: x * 0.05,
    lambda x: x * 0.07
]

interest_amount=np.piecewise(Account_balance,conditions,functions)
print(interest_amount.astype(int))

7212.65
20473.225
[ 550  725   75 2117 1540  437  156 3150  794  201]


In [ ]:
# Calculate the sum of each row using np.apply_along_axis
row_sums = np.apply_along_axis(np.sum, 1, bank_data)

# Print the resulting row sums
print(row_sums)

[13726.25 17332.4   5163.1  33086.   24809.8  11481.6   7971.75 47901.9
 18602.5   9451.  ]


####Question 16: Array Concatenation and Stacking

In [ ]:
Arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(Arr1)
Arr2=np.array([[9,10,11,12],[13,14,15,16]])
print(Arr2)

Horizontal_Array=np.hstack((Arr1,Arr2))
print(Horizontal_Array)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [ ]:
Arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(Arr1)
Arr2=np.array([[9,10,11,12],[13,14,15,16]])
print(Arr2)

Vertical_Array=np.vstack((Arr1,Arr2))
print(Vertical_Array)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
Arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(Arr1)
Arr2=np.array([[9,10,11,12],[13,14,15,16]])
print(Arr2)

Concatenat_Array0=np.concatenate((Arr1,Arr2),axis=0)
print(Concatenat_Array0)

Concatenat_Array1=np.concatenate((Arr1,Arr2),axis=1)
print(Concatenat_Array1)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [ ]:
Arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(Arr1)
Arr2=np.array([[9,10,11,12],[13,14,15,16]])
print(Arr2)

Depth_Array=np.dstack((Arr1,Arr2))
print(Depth_Array)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[[ 1  9]
  [ 2 10]
  [ 3 11]
  [ 4 12]]

 [[ 5 13]
  [ 6 14]
  [ 7 15]
  [ 8 16]]]


In [ ]:
Arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(Arr1)
Arr2=np.array([[9,10,11,12],[13,14,15,16]])
print(Arr2)

Col_Stack_Array=np.column_stack((Arr1,Arr2))
print(Col_Stack_Array)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


####Question 17: Array Splitting Operations

######Syntax:-np.split(array, indices_or_sections, axis=0)


In [ ]:
Arr=np.arange(9).reshape(3,3)
print(Arr)
Split=np.split(Arr,3,axis=0)
print(Split)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [ ]:
arr = np.arange(10)
print("Original array:", arr)

# Split the array at indices 2 and 5
split_arrays = np.split(arr, [2, 5])
print("Arrays after splitting:", split_arrays)

Original array: [0 1 2 3 4 5 6 7 8 9]
Arrays after splitting: [array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]


In [ ]:
Arr=np.array([[1,2,3,4],[5,6,7,8]])
print(Arr)

Horizontal_Array=np.hsplit(Arr,2)
print(Horizontal_Array)

[[1 2 3 4]
 [5 6 7 8]]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [ ]:
Arr=np.array([[1,2,3,4,5],[5,6,7,8,10]])
print(Arr)

vsplit_Array=np.vsplit(Arr,2)
print(vsplit_Array)

[[ 1  2  3  4  5]
 [ 5  6  7  8 10]]
[array([[1, 2, 3, 4, 5]]), array([[ 5,  6,  7,  8, 10]])]


In [ ]:
arr = np.arange(1,9)
print("Original array:", arr)
split_arrays_equal = np.array_split(arr, 3)
print( split_arrays_equal)

Original array: [1 2 3 4 5 6 7 8]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


####Question 18: Array Repetition and Tiling


In [ ]:
arr = np.arange(1,9)
print("Original array:", arr)
repeat_arrays = np.repeat(arr,2)
print( repeat_arrays)
repeat_arrays1 = np.repeat(arr,[3,1,3,1,3,1,3,1])
print( repeat_arrays1)

Original array: [1 2 3 4 5 6 7 8]
[1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8]
[1 1 1 2 3 3 3 4 5 5 5 6 7 7 7 8]


In [ ]:
arr = np.array([1, 2, 3])
print(arr)

tiled_array = np.tile(arr, 2)
print(tiled_array)

[1 2 3]
[1 2 3 1 2 3]


In [ ]:
arr_2d = np.array([[1, 2], [3, 4]])
print( arr_2d)

tiled_array_2d = np.tile(arr_2d, (2,2))
print(tiled_array_2d)

[[1 2]
 [3 4]]
[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


In [ ]:
Array_pattern = np.array([[0, 1],[1, 0]])
print(Array_pattern)

tiled_pattern = np.tile(Array_pattern, (4, 4))
print(tiled_pattern)

[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
arr = np.arange(1, 9)
print(arr)
repeat_counts = [1, 2, 1, 3, 2, 1, 4, 2]
print(repeat_counts)
repeat_arrays = np.repeat(arr, repeat_counts)
print(repeat_arrays)

[1 2 3 4 5 6 7 8]
[1, 2, 1, 3, 2, 1, 4, 2]
[1 2 2 3 4 4 4 5 5 6 7 7 7 7 8 8]


####Question 19: Array Comparison and Logical Operations

In [ ]:
Arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(Arr1)
Arr2=np.array([[9,10,11,12],[13,14,15,16]])
print(Arr2)

Eqal_Array=np.array_equal(Arr1,Arr2)
print(Eqal_Array)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
False


In [ ]:
Close_Array=np.allclose(Arr1,Arr2)
print(Close_Array)

False


In [ ]:
LogAnd_Array=np.logical_and(Arr1,Arr2)
print(LogAnd_Array)

[[ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
LogOr_Array=np.logical_or(Arr1,Arr2)
print(LogOr_Array)

[[ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
LogNot_Array=np.logical_not(Arr1)
print(LogNot_Array)

[[False False False False]
 [False False False False]]


####Question 20: Array Set Operations

In [ ]:
arr=np.array([1,1,3,4,4,6,7,3,10])
unique_Array=np.unique(arr)
print(unique_Array)

[ 1  3  4  6  7 10]


In [ ]:
Arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(Arr1)
Arr2=np.array([[5,6,7,8],[13,14,15,16]])
print(Arr2)

intersection_Array=np.intersect1d(Arr1,Arr2)
print(intersection_Array)

[[1 2 3 4]
 [5 6 7 8]]
[[ 5  6  7  8]
 [13 14 15 16]]
[5 6 7 8]


In [ ]:
Arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(Arr1)
Arr2=np.array([[5,6,7,8],[13,14,15,16]])
print(Arr2)
union_Array=np.union1d(Arr1,Arr2)
print(union_Array)

[[1 2 3 4]
 [5 6 7 8]]
[[ 5  6  7  8]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8 13 14 15 16]


In [ ]:
print(Arr1)
print(Arr2)
Setdef_Array=np.setdiff1d(Arr1,Arr2)
print(Setdef_Array)

[[1 2 3 4]
 [5 6 7 8]]
[[ 5  6  7  8]
 [13 14 15 16]]
[1 2 3 4]


In [ ]:
print(Arr1)
print(Arr2)
Dif_Array=np.setxor1d(Arr1,Arr2)
print(Dif_Array)

[[1 2 3 4]
 [5 6 7 8]]
[[ 5  6  7  8]
 [13 14 15 16]]
[ 1  2  3  4 13 14 15 16]


##Banking_2

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Customer_ID': range(1, 11),
    'Account_Balance': np.random.uniform(1000, 20000, 10).round(2),
    'Credit_Score': np.random.randint(300, 901, 10),
    'Transaction_Count': np.random.randint(1, 51, 10),
    'Years_Active': np.random.randint(1, 16, 10)
}

df = pd.DataFrame(data)
display(df)

Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0            1         14546.15           524                 21             5
1            2          9140.95           411                 40             7
2            3         14126.81           709                  3             2
3            4         14663.86           639                 21             6
4            5         10331.26           553                 48             7
5            6         15820.53           720                 49            15
6            7          8807.56           508                  8            12
7            8         12014.19           368                 42             3
8            9          3659.06           751                 36             2
9           10          8619.33           302                 29            13

In [ ]:
print(np.eye(4,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(np.zeros(8))

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print(np.ones(6))

[1. 1. 1. 1. 1. 1.]


In [ ]:
print(np.arange(0,15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
print(np.linspace(0,100,8))

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [ ]:
print(df.shape)

(10, 5)


In [ ]:
print(df.dtypes)

Customer_ID            int64
Account_Balance      float64
Credit_Score           int64
Transaction_Count      int64
Years_Active           int64
dtype: object


In [ ]:
print(df.size)

50


In [ ]:
print(df.ndim)

2


In [ ]:
print(df.memory_usage(deep=True).sum())
# AttributeError: `np.nbytes` was removed in the NumPy 2.0 release.
# Use `np.dtype(<dtype>).itemsize` instead.
#print(np.dbytes)

532


In [ ]:
print(df.iloc[0])

Customer_ID              1.00
Account_Balance      14546.15
Credit_Score           524.00
Transaction_Count       21.00
Years_Active             5.00
Name: 0, dtype: float64


In [ ]:
print(df.iloc[-1])

Customer_ID            10.00
Account_Balance      8619.33
Credit_Score          302.00
Transaction_Count      29.00
Years_Active           13.00
Name: 9, dtype: float64


In [ ]:
print(df.iloc[:,1])

0    14546.15
1     9140.95
2    14126.81
3    14663.86
4    10331.26
5    15820.53
6     8807.56
7    12014.19
8     3659.06
9     8619.33
Name: Account_Balance, dtype: float64


In [ ]:
print(df.iloc[:4,:3])

   Customer_ID  Account_Balance  Credit_Score
0            1         14546.15           524
1            2          9140.95           411
2            3         14126.81           709
3            4         14663.86           639


In [ ]:
print(df.iloc[3:8])

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
3            4         14663.86           639                 21             6
4            5         10331.26           553                 48             7
5            6         15820.53           720                 49            15
6            7          8807.56           508                  8            12
7            8         12014.19           368                 42             3


In [ ]:
min_balance =min(df['Account_Balance'])
max_balance =max(df['Account_Balance'])

print(f"Minimum account balance: {min_balance}")
print(f"Maximum account balance: {max_balance}")

Minimum account balance: 3659.06
Maximum account balance: 15820.53


In [ ]:
min_credit_score = df['Credit_Score'].min()
max_credit_score = df['Credit_Score'].max()

print(f"Minimum credit score: {min_credit_score}")
print(f"Maximum credit score: {max_credit_score}")

Minimum credit score: 302
Maximum credit score: 751


In [ ]:
percentiles = df['Account_Balance'].quantile([0.50])
print(percentiles)
percentiles1 = df['Account_Balance'].quantile([0.25,0.75])
print(percentiles1)

0.5    11172.725
Name: Account_Balance, dtype: float64
0.25     8890.9075
0.75    14441.3150
Name: Account_Balance, dtype: float64


In [ ]:
corel_ab_cs=df['Account_Balance'].corr(df['Credit_Score'])
print(corel_ab_cs)

0.15716392933429066


In [ ]:
cov_ab_cs=df['Account_Balance'].cov(df['Credit_Score'])
print(cov_ab_cs)

92434.43666666666


In [ ]:
reshape = df.values.reshape(5, 10)
print(reshape)

[[1.000000e+00 1.454615e+04 5.240000e+02 2.100000e+01 5.000000e+00
  2.000000e+00 9.140950e+03 4.110000e+02 4.000000e+01 7.000000e+00]
 [3.000000e+00 1.412681e+04 7.090000e+02 3.000000e+00 2.000000e+00
  4.000000e+00 1.466386e+04 6.390000e+02 2.100000e+01 6.000000e+00]
 [5.000000e+00 1.033126e+04 5.530000e+02 4.800000e+01 7.000000e+00
  6.000000e+00 1.582053e+04 7.200000e+02 4.900000e+01 1.500000e+01]
 [7.000000e+00 8.807560e+03 5.080000e+02 8.000000e+00 1.200000e+01
  8.000000e+00 1.201419e+04 3.680000e+02 4.200000e+01 3.000000e+00]
 [9.000000e+00 3.659060e+03 7.510000e+02 3.600000e+01 2.000000e+00
  1.000000e+01 8.619330e+03 3.020000e+02 2.900000e+01 1.300000e+01]]


In [ ]:
flatte_data = df.values.flatten()
print(flatte_data)

[1.000000e+00 1.454615e+04 5.240000e+02 2.100000e+01 5.000000e+00
 2.000000e+00 9.140950e+03 4.110000e+02 4.000000e+01 7.000000e+00
 3.000000e+00 1.412681e+04 7.090000e+02 3.000000e+00 2.000000e+00
 4.000000e+00 1.466386e+04 6.390000e+02 2.100000e+01 6.000000e+00
 5.000000e+00 1.033126e+04 5.530000e+02 4.800000e+01 7.000000e+00
 6.000000e+00 1.582053e+04 7.200000e+02 4.900000e+01 1.500000e+01
 7.000000e+00 8.807560e+03 5.080000e+02 8.000000e+00 1.200000e+01
 8.000000e+00 1.201419e+04 3.680000e+02 4.200000e+01 3.000000e+00
 9.000000e+00 3.659060e+03 7.510000e+02 3.600000e+01 2.000000e+00
 1.000000e+01 8.619330e+03 3.020000e+02 2.900000e+01 1.300000e+01]


In [ ]:
print(df.T)

                          0        1         2         3         4         5  \
Customer_ID            1.00     2.00      3.00      4.00      5.00      6.00   
Account_Balance    14546.15  9140.95  14126.81  14663.86  10331.26  15820.53   
Credit_Score         524.00   411.00    709.00    639.00    553.00    720.00   
Transaction_Count     21.00    40.00      3.00     21.00     48.00     49.00   
Years_Active           5.00     7.00      2.00      6.00      7.00     15.00   

                         6         7        8        9  
Customer_ID           7.00      8.00     9.00    10.00  
Account_Balance    8807.56  12014.19  3659.06  8619.33  
Credit_Score        508.00    368.00   751.00   302.00  
Transaction_Count     8.00     42.00    36.00    29.00  
Years_Active         12.00      3.00     2.00    13.00  


In [ ]:
# Calculate the midpoint for splitting
split_point = len(df) // 2

# Split the DataFrame into two parts
df_part1 = df.iloc[:split_point]
df_part2 = df.iloc[split_point:]

print("First part of the DataFrame:")
display(df_part1)

print("\nSecond part of the DataFrame:")
display(df_part2)

First part of the DataFrame:


Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0            1         14546.15           524                 21             5
1            2          9140.95           411                 40             7
2            3         14126.81           709                  3             2
3            4         14663.86           639                 21             6
4            5         10331.26           553                 48             7


Second part of the DataFrame:


Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
5            6         15820.53           720                 49            15
6            7          8807.56           508                  8            12
7            8         12014.19           368                 42             3
8            9          3659.06           751                 36             2
9           10          8619.33           302                 29            13

In [ ]:
# Calculate the midpoint for splitting columns
split_point_cols = len(df.columns) // 2

# Split the DataFrame into two parts horizontally
df_part1_h = df.iloc[:, :split_point_cols]
df_part2_h = df.iloc[:, split_point_cols:]

print("First part of the DataFrame (horizontal split):")
display(df_part1_h)

print("\nSecond part of the DataFrame (horizontal split):")
display(df_part2_h)

First part of the DataFrame (horizontal split):


Customer_ID  Account_Balance
0            1         14546.15
1            2          9140.95
2            3         14126.81
3            4         14663.86
4            5         10331.26
5            6         15820.53
6            7          8807.56
7            8         12014.19
8            9          3659.06
9           10          8619.33


Second part of the DataFrame (horizontal split):


Credit_Score  Transaction_Count  Years_Active
0           524                 21             5
1           411                 40             7
2           709                  3             2
3           639                 21             6
4           553                 48             7
5           720                 49            15
6           508                  8            12
7           368                 42             3
8           751                 36             2
9           302                 29            13

In [ ]:
high_balance_customers = df[df['Account_Balance'] > 10000]
display(high_balance_customers)

Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0            1         14546.15           524                 21             5
2            3         14126.81           709                  3             2
3            4         14663.86           639                 21             6
4            5         10331.26           553                 48             7
5            6         15820.53           720                 49            15
7            8         12014.19           368                 42             3

In [ ]:
high_credit_customers = df[df['Credit_Score'] > 800]
display(high_credit_customers)

Empty DataFrame
Columns: [Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active]
Index: []

In [ ]:
filtered_customers = df[(df['Transaction_Count'] < 50) & (df['Credit_Score'] > 750)]
display(filtered_customers)

Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
8            9          3659.06           751                 36             2

In [ ]:
highest_credit_customer_index = df['Credit_Score'].idxmax()
highest_credit_customer = df['Credit_Score'].max()
#highest_credit_customer = df.loc[highest_credit_customer_index]
#print("Customer with the highest credit score:")
#display(highest_credit_customer)
print(highest_credit_customer_index)
print(highest_credit_customer)

8
751


In [ ]:
# sorted_df = df.sort_values(by='Account_Balance', ascending=True)
# display(sorted_df)
sorted_df=df.iloc[np.argsort(df['Account_Balance'])]
display(sorted_df)

Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
8            9          3659.06           751                 36             2
9           10          8619.33           302                 29            13
6            7          8807.56           508                  8            12
1            2          9140.95           411                 40             7
4            5         10331.26           553                 48             7
7            8         12014.19           368                 42             3
2            3         14126.81           709                  3             2
0            1         14546.15           524                 21             5
3            4         14663.86           639                 21             6
5            6         15820.53           720                 49            15

In [ ]:
sorted_df_credit = df.sort_values(by='Credit_Score', ascending=False)
display(sorted_df_credit)

Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
8            9          3659.06           751                 36             2
5            6         15820.53           720                 49            15
2            3         14126.81           709                  3             2
3            4         14663.86           639                 21             6
4            5         10331.26           553                 48             7
0            1         14546.15           524                 21             5
6            7          8807.56           508                  8            12
1            2          9140.95           411                 40             7
7            8         12014.19           368                 42             3
9           10          8619.33           302                 29            13

In [ ]:
sorted_years_active = np.argsort(df['Years_Active'])
print(sorted_years_active)

0    2
1    8
2    7
3    0
4    3
5    1
6    4
7    6
8    9
9    5
Name: Years_Active, dtype: int64


In [ ]:
sorted_by_balance = df.sort_values(by='Account_Balance', ascending=False)
second_highest_balance_customer = sorted_by_balance.iloc[1]
display(second_highest_balance_customer)

Customer_ID              4.00
Account_Balance      14663.86
Credit_Score           639.00
Transaction_Count       21.00
Years_Active             6.00
Name: 3, dtype: float64

In [ ]:
lowest_transaction_count_index = df['Transaction_Count'].idxmin()
lowest_transaction_count_customer = df.loc[lowest_transaction_count_index]
display(lowest_transaction_count_customer)

Customer_ID              3.00
Account_Balance      14126.81
Credit_Score           709.00
Transaction_Count        3.00
Years_Active             2.00
Name: 2, dtype: float64

In [ ]:
absolute_values_df = df.abs()
display(absolute_values_df)

Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0            1         14546.15           524                 21             5
1            2          9140.95           411                 40             7
2            3         14126.81           709                  3             2
3            4         14663.86           639                 21             6
4            5         10331.26           553                 48             7
5            6         15820.53           720                 49            15
6            7          8807.56           508                  8            12
7            8         12014.19           368                 42             3
8            9          3659.06           751                 36             2
9           10          8619.33           302                 29            13

In [ ]:
account_balance_sqrt = np.sqrt(df['Account_Balance'])
display(account_balance_sqrt)

0    120.607421
1     95.608316
2    118.856258
3    121.094426
4    101.642806
5    125.779688
6     93.848601
7    109.609261
8     60.490164
9     92.840347
Name: Account_Balance, dtype: float64

In [ ]:
credit_score_squared = np.square(df['Credit_Score'])
display(credit_score_squared)

0    274576
1    168921
2    502681
3    408321
4    305809
5    518400
6    258064
7    135424
8    564001
9     91204
Name: Credit_Score, dtype: int64

In [ ]:
transaction_count_exp = np.exp(df['Transaction_Count'])
display(transaction_count_exp)

0    1.318816e+09
1    2.353853e+17
2    2.008554e+01
3    1.318816e+09
4    7.016736e+20
5    1.907347e+21
6    2.980958e+03
7    1.739275e+18
8    4.311232e+15
9    3.931334e+12
Name: Transaction_Count, dtype: float64

In [ ]:
account_balance_log = np.log(df['Account_Balance'])
display(account_balance_log)

0    9.585082
1    9.120520
2    9.555830
3    9.593141
4    9.242930
5    9.669064
6    9.083366
7    9.393844
8    8.204962
9    9.061763
Name: Account_Balance, dtype: float64

In [ ]:
cumulative_balance = np.cumsum(df['Account_Balance'])
display(cumulative_balance)

0     14546.15
1     23687.10
2     37813.91
3     52477.77
4     62809.03
5     78629.56
6     87437.12
7     99451.31
8    103110.37
9    111729.70
Name: Account_Balance, dtype: float64

In [ ]:
cumulative_transaction_count = np.cumprod(df['Transaction_Count'])
display(cumulative_transaction_count)

0                21
1               840
2              2520
3             52920
4           2540160
5         124467840
6         995742720
7       41821194240
8     1505562992640
9    43661326786560
Name: Transaction_Count, dtype: int64

In [ ]:
balance_difference = np.diff(df['Account_Balance'])
display(balance_difference)

array([-5405.2 ,  4985.86,   537.05, -4332.6 ,  5489.27, -7012.97,
        3206.63, -8355.13,  4960.27])

In [ ]:
balance_gradient = np.gradient(df['Account_Balance'])
display(balance_gradient)

array([-5405.2  ,  -209.67 ,  2761.455, -1897.775,   578.335,  -761.85 ,
       -1903.17 , -2574.25 , -1697.43 ,  4960.27 ])

In [ ]:
hist, bin_edges = np.histogram(df['Account_Balance'], bins=5)
print("Counts:", hist)
print("Bin Edges:", bin_edges)

Counts: [1 0 4 1 4]
Bin Edges: [ 3659.06   6091.354  8523.648 10955.942 13388.236 15820.53 ]


In [ ]:
dot_product = np.dot(df['Account_Balance'], df['Credit_Score'])
print( dot_product)

62115650.38000001


In [ ]:
account_balance_norm = np.linalg.norm(df['Account_Balance'])
print( account_balance_norm)

37099.36043264628


In [ ]:
matrix_3x3 = np.random.rand(3, 3)
display(matrix_3x3.astype(int))
determinant = np.linalg.det(matrix_3x3)
print("\nDeterminant of the matrix:", determinant)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])


Determinant of the matrix: 0.15334311510285714


In [ ]:
matrix_inverse = np.linalg.inv(matrix_3x3)
display(matrix_inverse)

array([[ 1.69228084,  0.66924104, -1.14051898],
       [-1.64309846,  2.79294687, -0.53359461],
       [ 0.19264112, -1.56679153,  1.77261901]])

In [ ]:
df['Customer_ID'] = df['Customer_ID'].astype(str)
display(df.dtypes)

Customer_ID           object
Account_Balance      float64
Credit_Score           int64
Transaction_Count      int64
Years_Active           int64
dtype: object

In [ ]:
contains_100 = df['Customer_ID'].str.contains('100')
display(df[contains_100])

Empty DataFrame
Columns: [Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active]
Index: []

In [ ]:
df['Customer_ID'] = df['Customer_ID'].str.upper()
display(df['Customer_ID'])

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Customer_ID, dtype: object

In [ ]:
customer_id_lengths = df['Customer_ID'].str.len()
display(customer_id_lengths)

0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    2
Name: Customer_ID, dtype: int64

In [ ]:
df['Customer_ID'] = df['Customer_ID'].str.replace('10', 'CUST')
display(df['Customer_ID'])

0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8
8       9
9    CUST
Name: Customer_ID, dtype: object

In [ ]:
df['Months_Active'] = df['Years_Active'] * 12
display(df)

Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active  \
0           1         14546.15           524                 21             5   
1           2          9140.95           411                 40             7   
2           3         14126.81           709                  3             2   
3           4         14663.86           639                 21             6   
4           5         10331.26           553                 48             7   
5           6         15820.53           720                 49            15   
6           7          8807.56           508                  8            12   
7           8         12014.19           368                 42             3   
8           9          3659.06           751                 36             2   
9        CUST          8619.33           302                 29            13   

   Months_Active  
0             60  
1             84  
2             24  
3             72  
4             84  
5            180  
6            144  
7             36  
8             24  
9            156

In [ ]:
average_years_active = df['Years_Active'].mean()
print(f"Average years active: {average_years_active}")

Average years active: 7.2


In [ ]:
long_term_customers = df[df['Years_Active'] > 5]
display(long_term_customers)

Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active  \
1           2          9140.95           411                 40             7   
3           4         14663.86           639                 21             6   
4           5         10331.26           553                 48             7   
5           6         15820.53           720                 49            15   
6           7          8807.56           508                  8            12   
9        CUST          8619.33           302                 29            13   

   Months_Active  
1             84  
3             72  
4             84  
5            180  
6            144  
9            156

In [ ]:
total_years_active = df['Years_Active'].sum()
print(f"Total years active for all customers: {total_years_active}")

Total years active for all customers: 72


In [ ]:
shortest_time_active_index = df['Years_Active'].idxmin()
shortest_time_active_customer = df.loc[shortest_time_active_index]
print("Customer with the shortest time active:")
display(shortest_time_active_customer)

Customer with the shortest time active:


Customer_ID                 3
Account_Balance      14126.81
Credit_Score              709
Transaction_Count           3
Years_Active                2
Months_Active              24
Name: 2, dtype: object

In [ ]:
def calculate_interest(balance):
  return balance * 0.05

df['Interest'] = df['Account_Balance'].apply(calculate_interest)
display(df)

Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active  \
0           1         14546.15           524                 21             5   
1           2          9140.95           411                 40             7   
2           3         14126.81           709                  3             2   
3           4         14663.86           639                 21             6   
4           5         10331.26           553                 48             7   
5           6         15820.53           720                 49            15   
6           7          8807.56           508                  8            12   
7           8         12014.19           368                 42             3   
8           9          3659.06           751                 36             2   
9        CUST          8619.33           302                 29            13   

   Months_Active  Interest  
0             60  727.3075  
1             84  457.0475  
2             24  706.3405  
3             72  733.1930  
4             84  516.5630  
5            180  791.0265  
6            144  440.3780  
7             36  600.7095  
8             24  182.9530  
9            156  430.9665

In [ ]:
low_balance_threshold = np.percentile(df['Account_Balance'], 25)
high_balance_threshold = np.percentile(df['Account_Balance'], 75)
df['Balance_Category'] = np.where(df['Account_Balance'] < low_balance_threshold, 'Low',
                                  np.where(df['Account_Balance'] < high_balance_threshold, 'Medium', 'High'))

print("Customers categorized by balance ranges:")
display(df[['Customer_ID', 'Account_Balance', 'Balance_Category']])

Customers categorized by balance ranges:


Customer_ID  Account_Balance Balance_Category
0           1         14546.15             High
1           2          9140.95           Medium
2           3         14126.81           Medium
3           4         14663.86             High
4           5         10331.26           Medium
5           6         15820.53             High
6           7          8807.56              Low
7           8         12014.19           Medium
8           9          3659.06              Low
9        CUST          8619.33              Low

In [ ]:
# low_credit_threshold = np.percentile(df['Credit_Score'], 25)
# high_credit_threshold = np.percentile(df['Credit_Score'], 75)
# conditions = [
#     (df['Credit_Score'] < low_credit_threshold),
#     (df['Credit_Score'] >= low_credit_threshold) & (df['Credit_Score'] < high_credit_threshold),
#     (df['Credit_Score'] >= high_credit_threshold)
# ]
conditions = [
    (df['Credit_Score'] < 580),
    (df['Credit_Score'] >= 580) & (df['Credit_Score'] < 670),
    (df['Credit_Score'] >= 670) & (df['Credit_Score'] < 740),
    (df['Credit_Score'] >= 740)
]
categories = ['Poor', 'Fair', 'Good', 'Excellent']

# Categorize customers using np.select
df['Credit_Score_Category'] = np.select(conditions, categories, default='Unknown')

print("Customers categorized by credit score ranges:")
display(df[['Customer_ID', 'Credit_Score', 'Credit_Score_Category']])

Customers categorized by credit score ranges:


Customer_ID  Credit_Score Credit_Score_Category
0           1           524                  Poor
1           2           411                  Poor
2           3           709                  Good
3           4           639                  Fair
4           5           553                  Poor
5           6           720                  Good
6           7           508                  Poor
7           8           368                  Poor
8           9           751             Excellent
9        CUST           302                  Poor

In [ ]:
numeric_df = df.select_dtypes(include=np.number)
row_sums = np.apply_along_axis(np.sum, 1, numeric_df.values)

display(row_sums)

array([15883.4575, 10139.9975, 15571.1505, 16135.053 , 11539.823 ,
       17575.5565,  9919.938 , 13063.8995,  4655.013 ,  9550.2965])

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concatenated_array = np.hstack((array1, array2))
display(array1)
display(array2)
display(concatenated_array)

array([1, 2, 3])

array([4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [ ]:
array1_v = np.array([[1, 2], [3, 4]])
array2_v = np.array([[5, 6], [7, 8]])
concatenated_array_v = np.vstack((array1_v, array2_v))
display(array1_v)
display(array2_v)
display(concatenated_array_v)

array([[1, 2],
       [3, 4]])

array([[5, 6],
       [7, 8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
array_a = np.array([[1, 2], [3, 4]])
array_b = np.array([[5, 6], [7, 8]])
concatenated_axis0 = np.concatenate((array_a, array_b), axis=0)
display(array_a)
display(array_b)
display(concatenated_axis0)

array_c = np.array([[1, 2, 3], [4, 5, 6]])
array_d = np.array([[7, 8, 9], [10, 11, 12]])
concatenated_axis1 = np.concatenate((array_c, array_d), axis=1)
display(array_c)
display(array_d)
display(concatenated_axis1)

array([[1, 2],
       [3, 4]])

array([[5, 6],
       [7, 8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

array([[1, 2, 3],
       [4, 5, 6]])

array([[ 7,  8,  9],
       [10, 11, 12]])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
array1_2d = np.array([[1, 2], [3, 4]])
array2_2d = np.array([[5, 6], [7, 8]])
stacked_array_d = np.dstack((array1_2d, array2_2d))
display(array1_2d)
display(array2_2d)
display(stacked_array_d)

array([[1, 2],
       [3, 4]])

array([[5, 6],
       [7, 8]])

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [ ]:
array_col1 = np.array([1, 2, 3, 4])
array_col2 = np.array([5, 6, 7, 8])
column_stacked_array = np.column_stack((array_col1, array_col2))
display(array_col1)
display(array_col2)
display(column_stacked_array)

array([1, 2, 3, 4])

array([5, 6, 7, 8])

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
array_to_split = np.arange(12)
display(array_to_split)
split_arrays = np.split(array_to_split, 3)
display(split_arrays)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [ ]:
array_to_split_indices = np.arange(10)
display(array_to_split_indices)
split_indices = [2, 5, 8]
split_arrays_indices = np.split(array_to_split_indices, split_indices)
display(split_arrays_indices)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7]), array([8, 9])]

In [ ]:
array_hsplit = np.arange(16).reshape(4, 4)
display(array_hsplit)
hsplit_equal = np.hsplit(array_hsplit, 2)
display(hsplit_equal)
hsplit_indices = np.hsplit(array_hsplit, [1, 3])
display(hsplit_indices)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
array_vsplit = np.arange(16).reshape(4, 4)
display(array_vsplit)
vsplit_equal = np.vsplit(array_vsplit, 2)
display(vsplit_equal)
vsplit_indices = np.vsplit(array_vsplit, [1, 3])
display(vsplit_indices)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [ ]:
array_to_array_split = np.arange(10)
display(array_to_array_split)

array_split_chunks = np.array_split(array_to_array_split, 3)
display(array_split_chunks)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [ ]:
array_to_repeat = np.array([1, 2, 3])
display(array_to_repeat)
repeated_array = np.repeat(array_to_repeat, 3)
display(repeated_array)

array([1, 2, 3])

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
array_to_tile = np.array([1, 2, 3])
display(array_to_tile)
tiled_array = np.tile(array_to_tile, 2)
display(tiled_array)

array([1, 2, 3])

array([1, 2, 3, 1, 2, 3])

In [ ]:
array_to_tile_2d = np.array([[1, 2], [3, 4]])
display(array_to_tile_2d)
tiled_array_2d = np.tile(array_to_tile_2d, (2, 3))
display(tiled_array_2d)

array([[1, 2],
       [3, 4]])

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [ ]:
pattern_unit = np.array([[0, 1], [1, 0]])
display(pattern_unit)
pattern = np.tile(pattern_unit, (4, 4))
display(pattern)

array([[0, 1],
       [1, 0]])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
Arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(Arr1)
Arr2=np.array([[9,10,11,12],[13,14,15,16]])
print(Arr2)

Eqal_Array=np.array_equal(Arr1,Arr2)
print(Eqal_Array)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
False


In [ ]:
Close_Array=np.allclose(Arr1,Arr2)
print(Close_Array)

False


In [ ]:
LogAnd_Array=np.logical_and(Arr1,Arr2)
print(LogAnd_Array)

[[ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
LogOr_Array=np.logical_or(Arr1,Arr2)
print(LogOr_Array)

[[ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
LogNot_Array=np.logical_not(Arr1)
print(LogNot_Array)

[[False False False False]
 [False False False False]]


In [ ]:
arr=np.array([1,1,3,4,4,6,7,3,10])
unique_Array=np.unique(arr)
print(unique_Array)

[ 1  3  4  6  7 10]


In [ ]:
Arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(Arr1)
Arr2=np.array([[5,6,7,8],[13,14,15,16]])
print(Arr2)

intersection_Array=np.intersect1d(Arr1,Arr2)
print(intersection_Array)

[[1 2 3 4]
 [5 6 7 8]]
[[ 5  6  7  8]
 [13 14 15 16]]
[5 6 7 8]


In [ ]:
Arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(Arr1)
Arr2=np.array([[5,6,7,8],[13,14,15,16]])
print(Arr2)
union_Array=np.union1d(Arr1,Arr2)
print(union_Array)

[[1 2 3 4]
 [5 6 7 8]]
[[ 5  6  7  8]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8 13 14 15 16]


In [ ]:
print(Arr1)
print(Arr2)
Setdef_Array=np.setdiff1d(Arr1,Arr2)
print(Setdef_Array)

[[1 2 3 4]
 [5 6 7 8]]
[[ 5  6  7  8]
 [13 14 15 16]]
[1 2 3 4]


In [ ]:
print(Arr1)
print(Arr2)
Dif_Array=np.setxor1d(Arr1,Arr2)
print(Dif_Array)

[[1 2 3 4]
 [5 6 7 8]]
[[ 5  6  7  8]
 [13 14 15 16]]
[ 1  2  3  4 13 14 15 16]
